# Arquivo de configuração para deploy no Google App Engine que veremos na aula 4

runtime: php55
api_version: 1

handlers:
  - url: /
    static_files: index.html
    upload: index.html
    http_headers: 
      Link: <assets/img/logo-alura.svg>; rel=preload; as=image, <assets/img/background-cidade-fundo.svg>; rel=preload; as=image

  - url: /assets
    static_dir: assets